package cn.com.startai.qx.utils;

public interface EventAction {

        String ACTION_LOGIN_RESULT = "ACTION_LOGIN_RESULT";
        String ACTION_LOGIN_EXPIRED = "ACTION_LOGIN_EXPIRED";
        String ACTION_DISCOVERY_START = "ACTION_DISCOVERY_START";
        String ACTION_DISCOVERY_STOP = "ACTION_DISCOVERY_STOP";
        String ACTION_DISCOVERY_RESULT = "ACTION_DISCOVERY_RESULT";

        String ACTION_SERVER_CONNECTED = "ACTION_SERVER_CONNECTED";
        String ACTION_SERVER_DISCONNECTED = "ACTION_SERVER_DISCONNECTED";
        String ACTION_SERVER_RECONNECTING = "ACTION_SERVER_RECONNECTING";

        String ACTION_HARDWARE_ACTIVATE_RESULT = "ACTION_HARDWARE_ACTIVATE_RESULT";
        String ACTION_REGISTER_RESULT = "ACTION_REGISTER_RESULT";
        String ACTION_LOGOUT_RESULT = "ACTION_LOGOUT_RESULT";

        String ACTION_GET_IDENTIFY_CODE_RESULT = "ACTION_GET_IDENTIFY_CODE_RESULT";
        String ACTION_CHECK_IDENTIFY_CODE_RESULT = "ACTION_CHECK_IDENTIFY_CODE_RESULT";
        String ACTION_BIND_RESULT = "ACTION_BIND_RESULT";
        String ACTION_BIND_EMAIL_RESULT = "ACTION_BIND_EMAIL_RESULT";
        String ACTION_BIND_THIRDACCOUNT_RESULT = "ACTION_BIND_THIRDACCOUNT_RESULT";
        String ACTION_UNBIND_THIRDACCOUNT_RESULT = "ACTION_UNBIND_THIRDACCOUNT_RESULT";
        String ACTION_BIND_MOBILE_RESULT = "ACTION_BIND_MOBILE_RESULT";
        String ACTION_GET_BIND_LIST_RESULT = "ACTION_GET_BIND_LIST_RESULT";
        String ACTION_UNBIND_RESULT = "ACTION_UNBIND_RESULT";
        String ACTION_SEND_EMAIL_RESULT = "ACTION_SEND_EMAIL_RESULT";
        String ACTION_GET_USERINFO_RESULT = "ACTION_GET_USERINFO_RESULT";
        String ACTION_UPDATE_USERINFO_RESULT = "ACTION_UPDATE_USERINFO_RESULT";
        String ACTION_UPDATE_DEVICE_INFO_RESULT = "ACTION_UPDATE_DEVICE_INFO_RESULT";
        String ACTION_UPDATE_USER_PWD_RESULT = "ACTION_UPDATE_USER_PWD_RESULT";
        String ACTION_GET_LATEST_VERSION_RESULT = "ACTION_GET_LATEST_VERSION_RESULT";
        String ACTION_RESET_LOGIN_PWE_RESULT = "ACTION_RESET_LOGIN_PWE_RESULT";
        String ACTION_CONNECT_DEVICE_RESULT = "ACTION_CONNECT_DEVICE_RESULT";
        String ACTION_PASSTHROUGH_RESULT = "ACTION_PASSTHROUGH_RESULT";
        String ACTION_UPDATE_REMARK_RESULT = "ACTION_UPDATE_REMARK_RESULT";

        String ACTION_DEVICEBEAN_STATUS_CHANE = "ACTION_DEVICEBEAN_STATUS_CHANE";
        String ACTION_NETWORK_CHANGE = "ACTION_NETWORK_CHANGE";
        String ACTION_UNACTIVATE_RESULT = "ACTION_UNACTIVATE_RESULT";
        String ACTION_ACTIVATE_RESULT = "ACTION_ACTIVATE_RESULT";
        String ACTION_MSG_ARRIVE = "ACTION_MSG_ARRIVE";

        String ACTION_RECOVERY_RESULT = "ACTION_RECOVERY_RESULT";
        String ACTION_UPDATE_VERSION_RESULT = "ACTION_UPDATE_VERSION";
        String ACTION_RENAME_RESULT = "ACTION_RENAME_RESULT";


    }
